#!/usr/bin/env python3
"""Build the deployable pages from src/site.html.

Outputs (all overwritten on every run):
  index.html      landing page that sends each visitor to the right store
  uk/index.html   UK store: GBP prices, UK delivery copy, the UK box line-up
  us/index.html   US store: USD prices, US shipping copy, the US box line-up

Edit src/site.html, then run:  python3 tools/build_sites.py
Never edit index.html, uk/ or us/ by hand: the next build replaces them.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / 'src' / 'site.html'
BASE_URL = 'https://ggraham1994.github.io/snacks-of-europe/'   # change when the stores get their own domains
ICON_V = 'v=3'

SITES = {
    'UK': dict(lang='en-GB', dir='uk', short='UK store', flag='🇬🇧',
               title='Snacks of Europe UK · European snack boxes delivered across the UK',
               desc='European snacks delivered UK-wide. Boxes from Germany, Italy, the Netherlands, Belgium, Poland, '
                    'France, Spain and Sweden, picked by locals and packed by hand. Free delivery over £40.',
               blurb='Prices in pounds. Free delivery over £40, tracked and at your door in 2–4 working days.'),
    'US': dict(lang='en-US', dir='us', short='US store', flag='🇺🇸',
               title='Snacks of Europe US · European snack boxes shipped across the USA',
               desc='European snacks shipped across the US. Boxes from Germany, Italy, the Netherlands, Belgium, Poland, '
                    'France, Spain and Britain, picked by locals and packed by hand. Free shipping over $49.',
               blurb='Prices in dollars. Free shipping over $49, tracked and delivered in 7–10 business days.'),
}
GENERATED = '<!-- Generated by tools/build_sites.py from src/site.html. Do not edit this file; edit the source and rebuild. -->\n'
BASE_STYLE = ('<style>html{color-scheme:light}body{margin:0;font:14px system-ui,sans-serif;background:#faf8f5}'
              'img{max-width:100%}[hidden]{display:none!important}</style>')


def icons(prefix):
    return (f'<link rel="icon" type="image/svg+xml" href="{prefix}favicon.svg?{ICON_V}">\n'
            f'<link rel="icon" type="image/png" sizes="32x32" href="{prefix}favicon-32.png?{ICON_V}">\n'
            f'<link rel="icon" type="image/png" sizes="192x192" href="{prefix}favicon-192.png?{ICON_V}">\n'
            f'<link rel="apple-touch-icon" href="{prefix}apple-touch-icon.png?{ICON_V}">\n')


def store_page(site, body):
    s = SITES[site]
    alternates = ''.join(f'<link rel="alternate" hreflang="{SITES[k]["lang"]}" href="{BASE_URL}{SITES[k]["dir"]}/">\n'
                         for k in SITES) + f'<link rel="alternate" hreflang="x-default" href="{BASE_URL}">\n'
    body = re.sub(r'(["\'(])images/', r'\1../images/', body)          # assets live one level up
    return (f'<!doctype html>\n{GENERATED}<html lang="{s["lang"]}">\n<head>\n<meta charset="utf-8">\n'
            f'<meta name="viewport" content="width=device-width, initial-scale=1">\n'
            f'<title>{s["title"]}</title>\n<meta name="description" content="{s["desc"]}">\n'
            f'<link rel="canonical" href="{BASE_URL}{s["dir"]}/">\n{alternates}'
            f'<meta property="og:title" content="{s["title"]}">\n<meta property="og:description" content="{s["desc"]}">\n'
            f'<meta property="og:type" content="website">\n<meta property="og:url" content="{BASE_URL}{s["dir"]}/">\n'
            f'<meta property="og:image" content="{BASE_URL}images/eu-22.webp">\n'
            f'{icons("../")}{BASE_STYLE}\n<script>window.SITE="{site}"</script>\n</head>\n<body>\n{body}\n</body>\n</html>\n')


def landing():
    cards = ''.join(
        f'<a class="card" href="{s["dir"]}/" hreflang="{s["lang"]}" data-site="{k}">'
        f'<span class="flag">{s["flag"]}</span><span class="name">{s["short"]}</span><span class="blurb">{s["blurb"]}</span>'
        f'<span class="go">Shop the {s["short"]} →</span></a>' for k, s in SITES.items())
    return f'''<!doctype html>
{GENERATED}<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Snacks of Europe · Choose your store</title>
<meta name="description" content="European snack boxes for the UK and the US. Choose your store to see prices and delivery for where you live.">
<link rel="canonical" href="{BASE_URL}">
<link rel="alternate" hreflang="en-GB" href="{BASE_URL}uk/">
<link rel="alternate" hreflang="en-US" href="{BASE_URL}us/">
<link rel="alternate" hreflang="x-default" href="{BASE_URL}">
{icons("")}<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@700;800&family=Figtree:wght@400;600;700&display=swap">
<script>
(function(){{
  try{{
    if(new URLSearchParams(location.search).has('choose'))return;
    var saved=localStorage.getItem('snacks-of-europe-site');
    var site=(saved==='UK'||saved==='US')?saved:null;
    if(!site){{
      var lang=(navigator.language||'').toLowerCase(),tz='';
      try{{tz=Intl.DateTimeFormat().resolvedOptions().timeZone||''}}catch(e){{}}
      site=(lang==='en-us'||/^America\\//.test(tz))?'US':'UK';
    }}
    location.replace(site.toLowerCase()+'/'+location.hash);
  }}catch(e){{}}
}})();
</script>
<style>
:root{{--cream:#FBF6EC;--ink:#1F1B2E;--ink-soft:#5A5670;--amber:#F5A524;--line:rgba(31,27,46,.12)}}
*{{box-sizing:border-box}}html{{color-scheme:light}}
body{{margin:0;min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:2rem 1rem;background:var(--cream);color:var(--ink);font-family:Figtree,system-ui,sans-serif;background-image:repeating-linear-gradient(135deg,#D8232A 0 18px,#fff 18px 36px,#2B4FA8 36px 54px,#fff 54px 72px);background-size:100% 8px;background-repeat:no-repeat}}
.brand{{display:flex;align-items:center;gap:.75rem;margin-bottom:1.5rem;text-decoration:none;color:inherit}}
.brand .mark{{width:44px;height:44px;border-radius:12px;background:#2B4FA8;display:grid;place-items:center;color:#FFD166;font-size:1.3rem}}
.brand b{{font-family:"Bricolage Grotesque",sans-serif;font-size:1.25rem;line-height:1.05;display:block}}
.brand small{{font-size:.68rem;font-weight:700;letter-spacing:.14em;text-transform:uppercase;color:#D8232A}}
h1{{font-family:"Bricolage Grotesque",sans-serif;font-size:clamp(1.8rem,4vw,2.6rem);margin:0 0 .4rem;text-align:center;letter-spacing:-.02em}}
p.lead{{margin:0 0 2rem;color:var(--ink-soft);text-align:center;max-width:34rem}}
.cards{{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:1rem;width:100%;max-width:680px}}
.card{{display:flex;flex-direction:column;gap:.35rem;padding:1.5rem;border:1px solid var(--line);border-radius:20px;background:#fff;text-decoration:none;color:inherit;box-shadow:0 10px 30px rgba(31,27,46,.06);transition:transform .15s,box-shadow .15s}}
.card:hover{{transform:translateY(-2px);box-shadow:0 16px 40px rgba(31,27,46,.12)}}
.flag{{font-size:2.4rem;line-height:1}}
.name{{font-family:"Bricolage Grotesque",sans-serif;font-size:1.35rem;font-weight:800;margin-top:.5rem}}
.blurb{{color:var(--ink-soft);line-height:1.45}}
.go{{margin-top:.75rem;font-weight:700;color:var(--ink);background:var(--amber);border-radius:999px;padding:.55rem 1rem;align-self:flex-start}}
.note{{margin-top:2rem;font-size:.85rem;color:var(--ink-soft);text-align:center}}
</style>
</head>
<body>
<a class="brand" href="?choose"><span class="mark">★</span><span><b>Snacks of<br>Europe</b><small>Snacks from home</small></span></a>
<h1>Choose your store</h1>
<p class="lead">Two stores, one warehouse of favourites. Pick where we are delivering and we will remember it next time.</p>
<div class="cards">{cards}</div>
<p class="note">Shipping somewhere else? The UK store delivers to Ireland and mainland Europe, the US store to Canada.</p>
<script>document.querySelectorAll('.card').forEach(function(a){{a.addEventListener('click',function(){{try{{localStorage.setItem('snacks-of-europe-site',a.dataset.site)}}catch(e){{}}}})}});</script>
</body>
</html>
'''


def main():
    src = SRC.read_text(encoding='utf-8')
    body = re.sub(r'^<meta charset="utf-8">\n<title>[^<]*</title>\n', '', src)   # the wrapper supplies its own
    for site, s in SITES.items():
        out = ROOT / s['dir'] / 'index.html'
        out.parent.mkdir(exist_ok=True)
        out.write_text(store_page(site, body), encoding='utf-8')
        print(f'wrote {out.relative_to(ROOT)} ({out.stat().st_size:,} bytes)')
    (ROOT / 'index.html').write_text(landing(), encoding='utf-8')
    print('wrote index.html (landing)')


if __name__ == '__main__':
    sys.exit(main())
