#!/usr/bin/env python3
"""Build the deployable pages from src/site.html.

Outputs (all overwritten on every run):
  index.html      silent router: sends each visitor to one store, with no picker
  uk/index.html   UK store: GBP prices, UK delivery copy, the UK box line-up
  us/index.html   US store: USD prices, US shipping copy, the US box line-up

Edit src/site.html, then run:  python3 tools/build_sites.py
Never edit index.html, uk/ or us/ by hand: the next build replaces them.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / 'src' / 'site.html'
BASE_URL = 'https://ggraham1994.github.io/snacks-of-europe/'   # change when the stores get their own domains
ICON_V = 'v=3'

SITES = {
    'UK': dict(lang='en-GB', dir='uk',
               title='Snacks of Europe UK · European snack boxes delivered across the UK',
               desc='European snacks delivered UK-wide. Boxes from Germany, Italy, the Netherlands, Belgium, Poland, '
                    'France, Spain and Sweden, picked by locals and packed by hand. Free delivery over £40.'),
    'US': dict(lang='en-US', dir='us',
               title='Snacks of Europe US · European snack boxes shipped across the USA',
               desc='European snacks shipped across the US. Boxes from Germany, Italy, the Netherlands, Belgium, Poland, '
                    'France, Spain and Britain, picked by locals and packed by hand. Free shipping over $49.'),
}
GENERATED = '<!-- Generated by tools/build_sites.py from src/site.html. Do not edit this file; edit the source and rebuild. -->\n'
BASE_STYLE = ('<style>html{color-scheme:light}body{margin:0;font:14px system-ui,sans-serif;background:#faf8f5}'
              'img{max-width:100%}[hidden]{display:none!important}</style>')


def icons(prefix):
    return (f'<link rel="icon" type="image/svg+xml" href="{prefix}favicon.svg?{ICON_V}">\n'
            f'<link rel="icon" type="image/png" sizes="32x32" href="{prefix}favicon-32.png?{ICON_V}">\n'
            f'<link rel="icon" type="image/png" sizes="192x192" href="{prefix}favicon-192.png?{ICON_V}">\n'
            f'<link rel="apple-touch-icon" href="{prefix}apple-touch-icon.png?{ICON_V}">\n')


def store_page(site, body):
    s = SITES[site]
    alternates = ''.join(f'<link rel="alternate" hreflang="{SITES[k]["lang"]}" href="{BASE_URL}{SITES[k]["dir"]}/">\n'
                         for k in SITES)
    body = re.sub(r'(["\'(])images/', r'\1../images/', body)          # assets live one level up
    return (f'<!doctype html>\n{GENERATED}<html lang="{s["lang"]}">\n<head>\n<meta charset="utf-8">\n'
            f'<meta name="viewport" content="width=device-width, initial-scale=1">\n'
            f'<title>{s["title"]}</title>\n<meta name="description" content="{s["desc"]}">\n'
            f'<link rel="canonical" href="{BASE_URL}{s["dir"]}/">\n{alternates}'
            f'<meta property="og:title" content="{s["title"]}">\n<meta property="og:description" content="{s["desc"]}">\n'
            f'<meta property="og:type" content="website">\n<meta property="og:url" content="{BASE_URL}{s["dir"]}/">\n'
            f'<meta property="og:image" content="{BASE_URL}images/eu-22.webp">\n'
            f'{icons("../")}{BASE_STYLE}\n<script>window.SITE="{site}"</script>\n</head>\n<body>\n{body}\n</body>\n</html>\n')


def landing():
    """Root page: routes each visitor to one store and offers no choice between them."""
    return f'''<!doctype html>
{GENERATED}<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Snacks of Europe</title>
<meta name="robots" content="noindex">
{icons("")}<script>
(function(){{
  var lang=(navigator.language||'').toLowerCase(),tz='';
  try{{tz=Intl.DateTimeFormat().resolvedOptions().timeZone||''}}catch(e){{}}
  var us=lang==='en-us'||/^America\\//.test(tz);
  location.replace((us?'us/':'uk/')+location.hash);
}})();
</script>
<noscript><meta http-equiv="refresh" content="0;url=uk/"></noscript>
<style>html{{color-scheme:light}}body{{margin:0;background:#FBF6EC}}</style>
</head>
<body></body>
</html>
'''


def main():
    src = SRC.read_text(encoding='utf-8')
    body = re.sub(r'^<meta charset="utf-8">\n<title>[^<]*</title>\n', '', src)   # the wrapper supplies its own
    for site, s in SITES.items():
        out = ROOT / s['dir'] / 'index.html'
        out.parent.mkdir(exist_ok=True)
        out.write_text(store_page(site, body), encoding='utf-8')
        print(f'wrote {out.relative_to(ROOT)} ({out.stat().st_size:,} bytes)')
    (ROOT / 'index.html').write_text(landing(), encoding='utf-8')
    print('wrote index.html (router)')


if __name__ == '__main__':
    sys.exit(main())
